### ISSUE TITLE
Kegunaan illuminate/mail

### ISSUE THREAD

**Issue by teguhkrniawan** [mrizkir/LearnBackendAndFrontProgramming#2]
Pak mohon penjelasan pustaka illuminate/mail studi kasusnya digunakan untuk apa

**Comment by mrizkir** [comment]
Illuminate\Mail digunakan untuk mengirimkan email. Misalnya saat user registrasi, atau pemberitahuan2.

**Comment by teguhkrniawan** [comment]
Mohon video penjelasan fetch data dari API(backend) di sisi frontend nya pak.Terimakasih Pak

**Comment by mrizkir** [comment]
Videonya belum dibuat. Jadi untuk sementara gunakan kode seperti dibawah ini :

```javascript
axios.get('/dmaster/asn/').then(({data})=>{   
                        console.log(data)
                    }).catch(({error})=>{
                        console.log(error)
                    });  
```
