### ISSUE TITLE
Instalasi Frontend

### ISSUE THREAD

**Issue by Nova27putra** [mrizkir/LearnBackendAndFrontProgramming#5]
Selamat siang, pak maaf saya baru menggunakan  aplikasi laragon untuk pertama kalinya 
pada instalasi beckend nya sudah saya terapkan pak.. untuk instalasi frontend saya mengalami warn .. bagaimana solusinya pak riski?
![Captureaskinginstallnpm](https://user-images.githubusercontent.com/37130149/81776591-4904e500-9519-11ea-8150-61e0309c865e.PNG)

**Comment by mrizkir** [comment]
coba ekseksusi perintah ini :
```
npm init

```

**Comment by Nova27putra** [comment]
Begini pak npm init
![Capturenpminit](https://user-images.githubusercontent.com/37130149/82010738-21d72080-969d-11ea-967e-08ba62637074.PNG)
