### ISSUE TITLE
Bertanya pak

### ISSUE THREAD

**Issue by aden65** [mrizkir/LearnBackendAndFrontProgramming#6]
![1589789487548537269644269029841](https://user-images.githubusercontent.com/57821013/82189648-e5fcbf00-9919-11ea-9a61-32e44eca9ea3.jpg)

Maaf pak, pas ketik "npm install vue" jadi gitu yah, itu sudah sukses apa error?

**Comment by itechnicyan** [comment]
Bantu jawab: pakai mode installasi yg Vue.cli saja pak.

**Comment by mrizkir** [comment]
coba pakai `npm init`
