### ISSUE TITLE
run App.vue

### ISSUE THREAD

**Issue by AsepSunanar** [mrizkir/LearnBackendAndFrontProgramming#8]
Bertanya Pa. Saya menggunakan Laragon, ketika mau menjalankan App.vue tidak bisa, padahal langkah2 istalasi semuanya sdh dijalankan dan sdh selesai, mohon penjelasan, terima kasih.

![2020-05-19_120324](https://user-images.githubusercontent.com/65584937/82286850-e99b4f00-99c8-11ea-8cb5-bba38c35e61e.jpg)

![2020-05-19_120537](https://user-images.githubusercontent.com/65584937/82286910-13ed0c80-99c9-11ea-8dac-6ef3777d6e97.jpg)

**Comment by mrizkir** [comment]
oh salah menjalankannya bukan seperti itu. Ketikan perintah berikut 
```bash
npm run serve
```

**Comment by AsepSunanar** [comment]
yang itu sdh pa, dan sdh tampil di browser nya. Maksud saya saya mau mengedit coding. Kan pertama dihapus dulu terus dibuat coding baru dr awal bapa menyampaikan materi.

**Comment by mrizkir** [comment]
iya benar itu.
